name: memobelc_front
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.1


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_modular: ^6.3.4
  http: ^1.2.2
  window_manager: ^0.4.2
  mobx: ^2.3.3+2
  flutter_mobx: ^2.2.1+1
  mobx_codegen: ^2.6.1
  protobuf: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.12


flutter:
  assets:
    - assets/images/

  uses-material-design: true

